sudo: required

language: cpp
compiler:
  - gcc

services:
  - docker

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_REF: github.com/P8P-7/core

addons:
  apt:
    packages:
      - doxygen

install:
  - docker build -t goliath .

script:
  - docker run -v $TRAVIS_BUILD_DIR:/core goliath
  - cd $TRAVIS_BUILD_DIR/doc
  - ./push_docs.sh
