sudo: required

language: cpp
compiler:
  - gcc

services:
  - docker

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_REF: github.com/P8P-7/core

install:
  - docker build -t goliath .
  - git clone https://github.com/doxygen/doxygen.git
  - cd doxygen
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ..
  - make
  - sudo make install


script:
  - docker run -v $TRAVIS_BUILD_DIR:/core goliath
  - cd $TRAVIS_BUILD_DIR/doc
  - ./push_docs.sh
